package com.gestion.entity;
// Generated 19 déc. 2017 18:45:41 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test1 generated by hbm2java
 */
@Entity
@Table(name = "test1", catalog = "x")
public class Test1 implements java.io.Serializable {

	private int id;

	public Test1() {
	}

	public Test1(int id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
