package com.gestion.entity;
// Generated 19 déc. 2017 17:16:22 by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "TEST")
public class Test implements java.io.Serializable {

	private BigDecimal id;

	public Test() {
	}

	public Test(BigDecimal id) {
		this.id = id;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
